import os
from dotenv import load_dotenv
import json
import tiktoken
from typing import List, Dict
from google import genai
from google.genai import types

load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")

enc = tiktoken.get_encoding("cl100k_base")

model_used = "gemini-3.6-flash"

class ContextCompressor:
    def __init__(self, model_name: str = model_used):
        # Automatically loads GEMINI_API_KEY from environment
        self.client = genai.Client()
        self.model_name = model_name

    def compress_chunk(self, query: str, chunk: Dict[str, str]) -> str:
        """
        Extracts only the critical factual sentences from a chunk that directly 
        relate to the query. Returns an empty string if irrelevant.
        """
        system_instruction = (
            "You are a strict context compression engine. Your job is to extract ONLY the exact, "
            "verbatim factual sentences or clauses from the provided text that are directly needed "
            "to answer the user's query.\n"
            "- Do NOT paraphrase or add explanations.\n"
            "- Strip all conversational filler, preambles, and unrelated technical details.\n"
            "- If the chunk contains NO relevant information to answer the query, output strictly NOTHING (empty string)."
        )

        prompt = f"""Target Query: {query}

Source Chunk Title: {chunk['title']}
Source Chunk Content:
\"\"\"{chunk['content']}\"\"\"

Extracted Relevant Snippet:"""

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.0, # Deterministic extraction
            ),
        )
        
        if response.text:
            return response.text.strip()
        return ""

    def compress_all(self, query: str, chunks: List[Dict[str, str]]) -> List[Dict[str, str]]:
        compressed_results = []
        for chunk in chunks:
            extracted_snippet = self.compress_chunk(query, chunk)
            if extracted_snippet:  # Discard chunks that compressed to empty
                compressed_results.append({
                    "chunk_id": chunk["chunk_id"],
                    "title": chunk["title"],
                    "extracted_content": extracted_snippet
                })
        return compressed_results


def count_token(text: str) -> int:
    return len(enc.encode(text))

# Sample query targeting specific operational metrics
QUERY = "What are the exact latency SLAs and refund policies for Tier 2 enterprise customers?"

# Mock retrieved chunks containing heavy corporate filler around critical facts
RETRIEVED_CHUNKS = [
    {
        "chunk_id": "chunk_101",
        "title": "Global Infrastructure & General Architecture Overview",
        "content": (
            "Our multi-region cloud deployment spans 14 data centers globally, ensuring high availability "
            "and redundancy across all standard workloads. Server provisioning follows strict SOC2 guidelines "
            "with zero-trust network policies implemented across all microservice boundaries. Internal routing "
            "is handled via distributed service meshes with automatic failover triggers. For Tier 2 enterprise "
            "customers, the guaranteed end-to-end API response latency SLA is strictly 150ms for the 99th percentile. "
            "Network monitoring telemetry runs at 10-second intervals to proactively detect localized jitter."
        )
    },
    {
        "chunk_id": "chunk_102",
        "title": "Billing Cycles and Standard Operational Terms",
        "content": (
            "Invoices are generated automatically on the 1st calendar day of each billing cycle and dispatched "
            "via electronic billing portals. Accounts must settle outstanding balances within net-30 payment terms "
            "to prevent automated service throttles or temporary suspension of provisioning dashboards. Tier 1 "
            "customers receive bespoke billing schedules with custom enterprise invoicing options upon request."
        )
    },
    {
        "chunk_id": "chunk_103",
        "title": "Service Level Agreement Credit and Refund Terms",
        "content": (
            "All SLA claims must be submitted in writing within 14 business days following the detected disruption. "
            "Incident reports generated by customer engineering teams are reviewed by our tier-3 operations staff. "
            "If SLA breaches exceed monthly allowances, Tier 2 enterprise customers are entitled to a 15% prorated "
            "service credit refund on their following monthly billing cycle. Hardware failures or routine scheduled "
            "maintenance windows are explicitly excluded from SLA credit calculations."
        )
    }
]

def synthesize_answer(query: str, context_text: str, model_name: str = model_used) -> str:
    """Generates the final answer strictly grounded in the provided context."""
    client = genai.Client()
    prompt = f"""Context Information:
\"\"\"
{context_text}
\"\"\"

User Question: {query}

Instructions: Answer the question using ONLY the facts from the context above. Be concise and precise."""

    response = client.models.generate_content(
        model=model_name,
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.0
        ),
    )
    return response.text.strip() if response.text else ""

if __name__ == "__main__":
    print("=== 1. RAW RETRIEVED CHUNKS ===")
    raw_context_parts = []
    total_raw_tokens = 0
    for chunk in RETRIEVED_CHUNKS:
        tokens = count_token(chunk["content"])
        total_raw_tokens += tokens
        raw_context_parts.append(f"[{chunk['title']}]\n{chunk['content']}")
        print(f"[{chunk['chunk_id']}] {chunk['title']} -> {tokens} tokens")
    
    raw_context_str = "\n\n".join(raw_context_parts)
    print(f"Total Raw Context Tokens: {total_raw_tokens}\n")

    # --- 2. Compression ---
    print("=== 2. RUNNING CONTEXT COMPRESSION ===")
    compressor = ContextCompressor()
    compressed_chunks = compressor.compress_all(QUERY, RETRIEVED_CHUNKS)

    compressed_context_parts = []
    total_compressed_tokens = 0
    for item in compressed_chunks:
        tokens = count_token(item["extracted_content"])
        total_compressed_tokens += tokens
        compressed_context_parts.append(f"[{item['title']}]\n{item['extracted_content']}")

    compressed_context_str = "\n\n".join(compressed_context_parts)
    reduction_pct = ((total_raw_tokens - total_compressed_tokens) / total_raw_tokens) * 100

    print(f"Total Compressed Context Tokens: {total_compressed_tokens}")
    print(f"Token Reduction: {reduction_pct:.2f}%\n")

    # --- 3. End-to-End Synthesis Comparison ---
    print("=== 3. SYNTHESIS: RAW CONTEXT ===")
    raw_answer = synthesize_answer(QUERY, raw_context_str)
    print(f"Answer:\n{raw_answer}\n")

    print("=== 4. SYNTHESIS: COMPRESSED CONTEXT ===")
    compressed_answer = synthesize_answer(QUERY, compressed_context_str)
    print(f"Answer:\n{compressed_answer}\n")